config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
   devise_scope :user do
   authenticated :user do
     root 'home#index', as: :authenticated_root
     post '/home/tokenize' => 'home#tokenize'
     get '/home/solvedGame' => 'home#solvedGame'
     get '/home/deleteGame' => 'home#deleteGame'
     get '/home/saved' => 'home#saved'
     get '/home/saved/:id' => 'home#show', as: 'game'
  
     
   end
  
   unauthenticated do
     root 'devise/sessions#new', as: :unauthenticated_root
   end
 end

end

app/models/game.rb
class Game < ActiveRecord::Base
    belongs_to :user
    validates :f1, :f2, :f3, :f4, :f5, :f6, :f7, :f8, :f9, :f10, :f11, :f12, :f13, :f14, :f15, :f16, presence: true,  length: {  :is => 1}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  alias :std_redirect_to :redirect_to
  def redirect_to(*args)
   flash.keep
   std_redirect_to *args
end
end

app/controllers/board_controller_controller.rb
class BoardControllerController < ApplicationController
    
    
  
    # def board_params
    #     params.require(:board).permit(:l1, :l2, :l3, :l4, :l5, :l6, :l7, :l8, :l9, :l10, :l11, :l12, :l13, :l14, :l15, :l16)
    # end
    
    # def create
    #     flash[:notice] = "Successfully created!"
    # end
    
    # def tokenize
    #     @letters = Array.new(4)
    #     puts (params[:letters])
    #     flash[:notice] = params[:letters]
    #     # add devise current_user.id add to params http://stackoverflow.com/questions/24101166/ruby-on-rails-and-devise-associating-id-from-one-table-to-a-foreign-key-id-in-an
    #     # redirect_to :back(request.parameters), :notice => "Post has been saved successfully."

    #     # redirect_to :back
    # end
    
    # # def solve
        
        
    # # end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def solvedGame
    @game =  Game.find_by_id(params[:game])
    
    letters= {"0"=> @game.f1, "1"=> @game.f2, "2"=> @game.f3, "3"=>@game.f4, "4" =>@game.f5, "5"=> @game.f6, "6"=> @game.f7, "7"=> @game.f8,"8"=> @game.f9,"9"=> @game.f10 , "10"=> @game.f11,"11"=> @game.f12,"12"=> @game.f13,"13"=> @game.f14,"14"=> @game.f15,"15"=> @game.f16    }

    @words = @game.f1+@game.f2+@game.f3+@game.f4+@game.f5+@game.f6+@game.f7+@game.f8+@game.f9+@game.f10+@game.f11+@game.f12+@game.f13+@game.f14+@game.f15+@game.f16
    
    require'unirest'#used for http request to api
    apirequest=Unirest.get "https://codebox-boggle-v1.p.mashape.com/"+letters.values.join.to_s, headers:{"X-Mashape-Key" => "dD07jz0voGmshZW6IXL7Ig9Jp883p1OzRPbjsnqogyFRjeOqfX","Accept" => "text/plain"}
    @answers = apirequest.body.sort_by(&:length).reverse!
    
    @answersLong = [];    @answersSix = [];    @answersFive = [];@answersFour = [];    @answersThree = [];
    @answers.each do |words| 
        if(words.length > 6) 
            @answersLong.push(words)
        end
        if(words.length == 6)
            @answersSix.push(words)
        end
        if(words.length == 5)
            @answersFive.push(words) 
        end
        if(words.length == 4)
            @answersFour.push(words)
        end
        if(words.length == 3)
            @answersThree.push(words)
        end
    end 
    
    # @answers.to_s.gsub!(/[!@%&"]/,'')
  end
 def deleteGame
Game.destroy(params[:game])
redirect_to :back
end

    def tokenize 
       if letter 
           #store the input game in the db
           @new_game = Game.create!(f1: params[:letters][:"0"], f2: params[:letters][:"1"], f3: params[:letters][:"2"], f4: params[:letters][:"3"], f5: params[:letters][:"4"], f6: params[:letters][:"5"], f7: params[:letters][:"6"], f8: params[:letters][:"7"], f9: params[:letters][:"8"], f10: params[:letters][:"9"], f11: params[:letters][:"10"], f12: params[:letters][:"11"], f13: params[:letters][:"12"], f14: params[:letters][:"13"], f15: params[:letters][:"14"], f16: params[:letters][:"15"], user_id: current_user.id, gameName: params[:game])
        
        
            redirect_to home_solvedGame_path(:game => @new_game.id) 
   
       else
            flash[:notice] = "Error: please input a letter into every box";redirect_to :back
        
       end
       
       
    end
    

    
    # def submit
      
    # end
    
    
    def letter
        return (params[:letters][:"0"].match /[A-Za-z]/) && (params[:letters][:"1"].match /[A-Za-z]/) && (params[:letters][:"2"].match /[A-Za-z]/) && (params[:letters][:"3"].match /[A-Za-z]/) && (params[:letters][:"4"].match /[A-Za-z]/) && (params[:letters][:"5"].match /[A-Za-z]/) && (params[:letters][:"6"].match /[A-Za-z]/) && (params[:letters][:"7"].match /[A-Za-z]/) && (params[:letters][:"8"].match /[A-Za-z]/) && (params[:letters][:"9"].match /[A-Za-z]/) && (params[:letters][:"10"].match /[A-Za-z]/) && (params[:letters][:"11"].match /[A-Za-z]/) && (params[:letters][:"12"].match /[A-Za-z]/) && (params[:letters][:"13"].match /[A-Za-z]/) && (params[:letters][:"14"].match /[A-Za-z]/) && (params[:letters][:"15"].match /[A-Za-z]/)
    end
    
    # def letter?(lookAhead)
    #     lookAhead =~ /[[:alpha:]]/
    # end

    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_controller_helper.rb
module BoardControllerHelper
end

app/helpers/home_helper.rb
module HomeHelper

    
end

app/views/home/game.html.erb
<meta name="viewport" content="width=device-width, initial-scale=0.9">
<body id = "home">
    <% if user_signed_in? %>
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Home
                    </a>
                </li>
                <li>
                    <a href="#">Dashboard</a>
                </li>
                <li>
                    <a href="#">New Game</a>
                </li>
                <li>
                    <a href="#">View Saved Game</a>
                </li>
                <li>
                    <a href="#">Save Game</a>
                </li>
                <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                    <!--<a href="#">Contact</a>-->
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class = "header">
                            <h1>Welcome to the Boggle Solver!</h1>
                            <!--<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        -->
                          </div>
                        
                        <!--<p>Find me in app/views/home/index.html.erb</p>-->
                        <!--<% if user_signed_in? %>-->
                          <!--<li>-->
                          <!--<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        -->
                          <!--</li>-->
                          <%= form_tag ('/home/tokenize') do %>
                          
                          <div class = "holder">
                            <div class = "cells">
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[0]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[1]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[2]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[3]" style="text-align:center;" /> 
                            </div>
                          </div>
                           <div class = "holder">
                            <div class = "celss">
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[4]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[5]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[6]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[7]" style="text-align:center;" /> 
                            </div>
                          </div>
                           <div class = "holder">
                            <div class = "cells">
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[8]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[9]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[10]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[11]" style="text-align:center;" /> 
                            </div>
                          </div>
                           <div class = "holder">
                            <div class = "cell">
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[12]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[13]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[14]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1"name= "letters[15]"  style="text-align:center;" /> 
                            </div>
                          </div>
                          <div class = "button">
                              <%= button_to 'Submit', :controller =>'home', :action => 'tokenize', :method => :post, :remote => true %>
                              <!--<input type="submit" value="Submit" onclick="return getLetters();">-->
                          </div>
                          
                          <div class = "errors">
                              <% if notice %>
                                   <% flash.each do |name, msg| %>
                                   <%= content_tag :div, msg, class: "words" %>
                                   <% end %>
                               <% end %>
                          </div>
                           
                         <div class = "paragraph">
                             <div class= words>
                                  <p>Input letters into the text boxes exactly as they appear on your Boggle board, then click submit.
                                  After submitting <br>your letters you will be navigated to page containing all possible words from the set
                                  of submitted letters.</p>
                              </div>
                         </div>
                          <br>
                          <br>
                          
                          <%= submit_tag 'Save Changes' %>
                 
                          <%= link_to 'Solve', home_tokenize_path, method: :get %>
                          <!--<% end %>-->
                     
                          <%= debug (params) %>
                      
                        <% end %>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
     <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
    <% end %>
    
    <%= flash[:notice] if flash[:notice] %>
    "Current number of Games" <%= Game.all.count %>
</body>

app/views/home/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=0.9">
<body id = "home">
    <% if user_signed_in? %>
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <!--<li class="sidebar-brand">-->
                <!--    <a href="#">-->
                <!--        Home-->
                <!--    </a>-->
                <!--</li>-->
                <br>
                </br>
                <li>
                    <!--<a href="#">View Saved Games</a> home#saved-->
                    <%= link_to('View Saved', home_saved_url, :method => :get) %>
                </li>
                <li>
                    <!--<a href="#">New Game</a>-->
                    <%= link_to 'New Game', home_index_url %>
                </li>
                <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                    <!--<a href="#">Contact</a>-->
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class = "header">
                            <h1>Welcome to the Boggle Solver!</h1>
                            <!--<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        -->
                          </div>
                        
                        <!--<p>Find me in app/views/home/index.html.erb</p>-->
                        <!--<% if user_signed_in? %>-->
                          <!--<li>-->
                          <!--<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        -->
                          <!--</li>-->
                          <%= form_tag ('/home/tokenize') do %>
                          
                          <div class = "holder">
                            <div class = "cells">
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[0]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[1]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[2]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[3]" style="text-align:center;" /> 
                            </div>
                          </div>
                           <div class = "holder">
                            <div class = "celss">
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[4]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[5]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[6]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[7]" style="text-align:center;" /> 
                            </div>
                          </div>
                           <div class = "holder">
                            <div class = "cells">
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[8]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[9]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[10]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[11]" style="text-align:center;" /> 
                            </div>
                          </div>
                           <div class = "holder">
                            <div class = "cell">
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[12]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[13]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1" name= "letters[14]" style="text-align:center;" /> 
                              <input type = "text" id = "text1" value = "<%= %>" size = "4" maxlength= "1"name= "letters[15]"  style="text-align:center;" /> 
                            </div>
                          </div>
                          <h5><center><font color="white">Game Name:</center></h5></font>
                          <div class = "holder">
                              <div class = "cell">
                                  <input type = "text" id = "game" value = "<%= %>" size = "10" maxlength = "18" name = "game" style="text-align:center;" />
                              </div>
                          </div>
                          <div class = "button">
                              <%= button_to 'Submit', :controller =>'home', :action => 'tokenize', :method => :post, :remote => true %>
                              <!--<input type="submit" value="Submit" onclick="return getLetters();">-->
                          </div>
                          
                          <% if notice %>
                          <div class = "errors">
                              <% if notice %>
                                   <% flash.each do |name, msg| %>
                                   <%= content_tag :div, msg, class: "words" %>
                                   <% end %>
                               <% end %>
                          </div>
                                <% end %>
                         <div class = "paragraph">
                             <div class= words>
                                  <p>Input letters into the text boxes exactly as they appear on your Boggle board, then click submit.
                                  After submitting <br>your letters you will be navigated to page containing all possible words from the set
                                  of submitted letters.</p>
                              </div>
                         </div>
                          <br>
                          <br>
                          
                     
                          <!--<% end %>-->
                     
                        <% end %>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
     <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
    <% end %>

</body>

app/views/home/saved.html.erb
<meta name="viewport" content="width=device-width, initial-scale=0.9">
<body id = "home">
    <% if user_signed_in? %>
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <!--<li class="sidebar-brand">-->
                <!--    <a href="#">-->
                <!--        Home-->
                <!--    </a>-->
                <!--</li>-->
                <br>
                </br>
                <li>
                    <!--<a href="#">View Saved Games</a> home#saved-->
                    <%= link_to('View Saved', home_saved_url, :method => :get) %>
                </li>
                <li>
                    <!--<a href="#">New Game</a>-->
                    <%= link_to 'New Game', home_index_url %>
                </li>
                <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                    <!--<a href="#">Contact</a>-->
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <table class="table-fill">
              <tr>
                <th class="text-center">Game Name</th>
                <th class="text-center">Creation Date</th>
                <th class="text-center">Updated At</th>
                <th class="text-center">Delete</th>

              </tr>
                
                <% Game.all.each do |game| %>
                    <% if game.user_id == current_user.id%>
                       <!--<li><%= link_to home_saved_url %>zz</li>-->
                        <tr >
                            <td data-link="<%= home_solvedGame_path(:game => game.id) %>" class="text-center"><%= game.gameName.titleize %></td>
                            <td data-link="<%= home_solvedGame_path(:game => game.id) %>" class="text-center"><%= game.created_at %></td>
                            <td data-link="<%= home_solvedGame_path(:game => game.id) %>" class="text-center"><%= game.updated_at %></td>
                            <td data-link="<%= home_deleteGame_path(:game => game.id) %>"class="text-center">Delete</td>
                        </tr>
                        
                    <% end %>
                <% end %>

            </table>
            
        </div>

        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
     <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
    <% end %>
    
    <%= flash[:notice] if flash[:notice] %>
    "Current number of Games" <%= Game.all.count %>
</body>

app/views/home/solvedGame.html.erb
<meta name="viewport" content="width=device-width, initial-scale=0.9">
<body id = "home">
    <% if user_signed_in? %>
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <br>
                </br>
                <li>
                    <!--<a href="#">View Saved Games</a> home#saved-->
                    <%= link_to('View Saved', home_saved_url, :method => :get) %>
                </li>
                <li>
                    <!--<a href="#">New Game</a>-->
                    <%= link_to 'New Game', home_index_url %>
                </li>
                <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                    <!--<a href="#">Contact</a>-->
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class = "header">
                            <h1>Solutuon for <%=@game.gameName%>!</h1>
                          </div>
                        
                                              <%= form_tag ('/home/tokenize') do %>

                          
                          <div class = "holder">
                            <div class = "cells">
                              <input type = "text" id = "text1" value = <%= @letters["0"] %> size = "4" maxlength= "1" name= "letters[0]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = <%= @letters["1"] %> size = "4" maxlength= "1" name= "letters[1]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = <%= @letters["2"] %> size = "4" maxlength= "1" name= "letters[2]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = <%= @letters["3"] %> size = "4" maxlength= "1" name= "letters[3]" style="text-align:center;" readonly/> 
                            </div>
                          </div>
                           <div class = "holder">
                            <div class = "celss">
                              <input type = "text" id = "text1" value = <%= @letters["4"] %> size = "4" maxlength= "1" name= "letters[4]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = <%= @letters["5"] %> size = "4" maxlength= "1" name= "letters[5]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = <%= @letters["6"] %> size = "4" maxlength= "1" name= "letters[6]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = <%= @letters["7"] %> size = "4" maxlength= "1" name= "letters[7]" style="text-align:center;" readonly/> 
                            </div>
                          </div>
                           <div class = "holder">
                            <div class = "cells">
                              <input type = "text" id = "text1" value = "<%=@letters["8"] %>" size = "4" maxlength= "1" name= "letters[8]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = "<%=@letters["9"] %>" size = "4" maxlength= "1" name= "letters[9]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = "<%=@letters["10"] %>" size = "4" maxlength= "1" name= "letters[10]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = "<%= @letters["11"]%>" size = "4" maxlength= "1" name= "letters[11]" style="text-align:center;" readonly/> 
                            </div>
                          </div>
                           <div class = "holder">
                            <div class = "cell">
                              <input type = "text" id = "text1" value = <%= @letters["12"] %> size = "4" maxlength= "" name= "letters[12]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = "<%=@letters["13"] %>" size = "4" maxlength= "1" name= "letters[13]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = "<%=@letters["14"] %>" size = "4" maxlength= "1" name= "letters[14]" style="text-align:center;" readonly/> 
                              <input type = "text" id = "text1" value = "<%= @letters["15"]%>" size = "4" maxlength= "1"name= "letters[15]"  style="text-align:center;" readonly/> 
                            </div>
                          </div>
                          <div class = "button">
                          </div>
                          
                       
                      
                 
                          <% end %>
                     
                        <% end %>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
        <div class = "answers">
             <div class = "solution">
             Answers
             </div>
         <div class = "paragraph">
             <!--<div class = "words">-->
            <table class="table2">
                <tr>
                    
                    
                    
                    <th> Seven+ </th>
                    <th> Six </th>
                    <th> Five </th>
                    <th> Four </th>
                    <th> Three </th>
                    
                </tr>
                
                <tr>
                   
                    <td>
                        <%@answersLong.each do |word|%>
                            <%= word%><br/>
                        <%end%>
                    </td>
                    <td>
                        <%@answersSix.each do |word|%>
                            <%=word%><br/>
                        <%end%>
                    </td>
                    <td>
                        <%@answersFive.each do |word|%>
                            <%=word%><br/>
                        <%end%>
                    </td>
                    <td>
                        <%@answersFour.each do |word|%>
                            <%=word%><br/>
                        <%end%>
                    </td>
                   
                    
                    <td>
                        <%@answersThree.each do |word|%>
                            <%=word%><br/>
                        <%end%>
                    </td>
                    
                </tr>
                
            
            
            </table>
             <!--</div>-->
         </div>
        </div>
    </div>
    <!-- /#wrapper -->
     <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Un-Boggle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>